### ISSUE TITLE
BioPerl version dependency

### ISSUE THREAD

**Issue by hobrien** [bioperl/bp-utils#1]
Hi there,

Thanks for making these available. They seem like they have the potential to be quite useful.

I just wanted to let you know that bioseq and bioaln -D did't work with my older version of BioPerl (1.6902). After updating bioperl everything seems to be fine. Might be worth mentioning in the documentation. Cheers!

**Comment by weigangq** [comment]
thanks for feedback.

Do you have a good way of retrieving BioPerl version? I tried the following
recommended way:

perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION,"\n"'

which gets "1.006924", which doesn't seem to be the expected 1.6 version.

thanks,

weigang

**Comment by hobrien** [comment]
Hi Weigang,

That confused me this morning also. 1.006924 is version 1.6.924, which I think is the current one. I have no idea why they do it that way. The instructions should really say 

perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION*100-99,"\n�'

all good things,
 Heath

**Comment by Leont** [comment]
> 1.006924 is version 1.6.924, which I think is the current one. I have no idea why they do it that way.

This follows the perl convention for converting a semantic version into a number.

```
$ perl -Mversion -E 'say version->new("1.6.924")->numify'
1.006924
```

**Comment by weigangq** [comment]
thanks for clarification.

weigang

**Comment by yzhernand** [comment]
I've just pushed an update to the README file which should close this bug. The change indicates that the required version of BioPerl is v1.6.924. I'm not sure that an earlier version works as well, but this is at least more accurate than what was indicated previously.

I also added instructions on how users might check if they have the right version.
