### ISSUE TITLE
Just a note to be aware of modules in core being split out in separate distributions

### ISSUE THREAD

**Issue by cjfields** [bioperl/bp-utils#15]
@carandraug is working on splitting dependency-related code out of the core distribution into separate distributions for release on CPAN.  See the [`Changes`](https://github.com/bioperl/bioperl-live/blob/master/Changes) log for updates.

**Comment by carandraug** [comment]
Basically, instead of listing a depency on `'Bio::Root::Version` (which you don't actually use anywhere), you should instead list:

```
Bio::Align::DNAStatistics          = 0
Bio::AlignIO                       = 0
Bio::Align::Utilities              = 0
Bio::BPWrapper                     = 0
Bio::CodonUsage::IO                = 0
Bio::DB::GenBank                   = 0
Bio::LocatableSeq                  = 0
Bio::PopGen::Population            = 0
Bio::PopGen::Statistics            = 0
Bio::PopGen::Utilities             = 0
Bio::Restriction::Analysis         = 0
Bio::Restriction::EnzymeCollection = 0
Bio::SearchIO                      = 0
Bio::Seq                           = 0
Bio::SeqIO                         = 0
Bio::SeqUtils                      = 0
Bio::SimpleAlign                   = 0
Bio::Tools::CodonTable             = 0
Bio::Tools::IUPAC                  = 0
Bio::Tools::SeqStats               = 0
Bio::TreeIO                        = 0
Bio::Tree::Node                    = 0
Bio::Tree::Tree                    = 0
Bio::Tree::TreeFunctionsI          = 0
constant                           = 0
Data::Dumper                       = 0
Exporter                           = 0
File::Basename                     = 0
FindBin                            = 0
lib                                = 0
List::Util                         = 0
perl                               = 5.010
Pod::Usage                         = 0
POSIX                              = 0
Scalar::Util                       = 0
strict                             = 0
vars                               = 0
warnings                           = 0
```

Consider using something to automatically find your dependencies at dependency time and automatically generate your `Build.PL` with that info

**Comment by yzhernand** [comment]
Hi Chris, thanks for the heads up. Do you think we should go ahead and make the switch to Dist::Zilla as well to accomplish this?

I can work on porting this to use Dist::Zilla if no one objects.

**Comment by cjfields** [comment]
@yzhernand yes I'd recommend it, if nothing more than to make releases easier.   We are also switching away from `Bio::Root::Version` alludes to.

**Comment by rocky** [comment]
@yzhernand  Never have had an objection to switching to Dist::Zilla and sorrry for not seeing/responding sooner. 

As far as I am concerned, do it anytime you want.

@cjfields @carandraug  the next upcoming release will remove `Bio::Root::Version` and use `Bio::Restriction::Analysis` instead.  (It is currently in commit bbf870d)

**Comment by rocky** [comment]
@cjfields @carandraug With release 1.13 on [CPAN](https://metacpan.org/release/ROCKY/Bio-BPWrapper-1.13) and [tagged in this repository](https://github.com/bioperl/p5-bpwrapper/releases/tag/release-1.13) we've stopped using `Bio::Root:Version`

Thanks for the advance notice and my apologies for not replying and fixing sooner.
