### ISSUE TITLE
Bio::SeqFeature::Tools::Unflattener does not convert pseudogene correctly

### ISSUE THREAD

**Issue by sufenhu9** [bioperl/bp-utils#3]
When I use Bio::SeqFeature::Tools::Unflattener to convert GenBank flat-feature-list to containment hierarchy, 
$unflattener->unflatten_seq(-seq=>$seq, -use_magic=>1);

Everything is fine except these genes has pseudo tag. 
1. Gene and CDS with pseudo tag have been convert to pseudogene and pseudoCDS, but they are flat. That is means the pseudoCDS is not the child of the pseudogene. 
2. Gene and tRNA with pseudo tag have been convert to pseudogene and pseudotRNA, but they are not nested either. The converted pseudotRNA are not the child of the pseudogene.

Like to know if there is any other parameter, or any other method that I can use to convert both gene and pseudogene correctly.
###### sample file

http://www.ncbi.nlm.nih.gov/nuccore/FR823391
http://www.ncbi.nlm.nih.gov/nuccore/GL636509
###### sample codes
# !/usr/bin/perl

use strict;
use Bio::SeqIO;
use Bio::Seq::SeqBuilder;
use Bio::Species;
use Bio::Annotation::SimpleValue;
use Bio::SeqFeature::Tools::Unflattener;

my $seq_in = Bio::SeqIO->new ('-file' => "<$ARGV[0]", '-format' => 'Genbank');
my $unflattener = Bio::SeqFeature::Tools::Unflattener->new;

while (my $bioperlSeq = $seq_in->next_seq() ) {
  if(!($bioperlSeq->molecule =~ /rna/i)){
    $unflattener->error_threshold(1);
    $unflattener->report_problems(*STDERR);
    $unflattener->unflatten_seq(-seq=>$bioperlSeq,
                                 -use_magic=>1);

```
my @topSeqFeatures = $bioperlSeq->get_SeqFeatures;

$bioperlSeq->remove_SeqFeatures;

foreach my $bioperlFeatureTree (@topSeqFeatures) {
  my $type = $bioperlFeatureTree->primary_tag();
  if (($bioperlFeatureTree->has_tag("locus_tag"))){
my ($cID) = $bioperlFeatureTree->get_tag_values("locus_tag");
print STDERR "\nprocessing $cID...\n";
  }

  if ($type =~ /pseudogene/i || $type =~ /pseudotRNA/i || $type =~ /pseudoCDS/i ) {
foreach my $subPseuFeat ($bioperlFeatureTree->get_SeqFeatures) {
  my $subPseuType = $subPseuFeat->primary_tag();
  print STDERR "  subPseuType = $subPseuType\n";
    my @pseuLocs = $subPseuFeat->location;
    foreach my $pseuLoc (@pseuLocs) {
      my $pseuLocStart = $pseuLoc->start();
      my $pseuLocEnd = $pseuLoc->end();
      print "    pseuLoc location : $pseuLocStart ... $pseuLocEnd\n";
    }
}
  }
print STDERR "\$type = $type\n";
foreach my $subFeat ($bioperlFeatureTree->get_SeqFeatures) {
  my $subType = $subFeat->primary_tag();
  print STDERR "  subType = $subType\n";
  foreach my $subSubFeat ($subFeat->get_SeqFeatures) {
    my $subSubType = $subSubFeat->primary_tag();
    print STDERR "      subSubType = $subSubType\n";
    if ($subSubType eq "CDS" || $subSubType eq "exon" ) {
      my @CDSLocs = $subSubFeat->location;
      foreach my $CDSLoc (@CDSLocs) {
    my $subSubStart = $CDSLoc->start();
    my $subSubEnd = $CDSLoc->end();
    print STDERR "            location: $subSubStart .... $subSubEnd\n";
      }
    }
  }
}
}
```

  }
}

I am using bioperl_live/1.6.9,
$ perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION,"\n"'
1.0069

Everything is fine when I use bioperl version 1.4. Not sure what is changed for Bio::SeqFeature::Tools::Unflattener between 1.4 and 1.6.9.

The different outputs with above code in different bioperl version 1.6.9 and 1.4.
###### #  BioPerl 1.6.9

processing NCLIV_047911...
$type = pseudogene
processing NCLIV_047911...
$type = pseudoCDS
###### #  BioPerl 1.4

processing NCLIV_047911...
$type = gene
  subType = mRNA
      subSubType = CDS
            location: 2628722 .... 2629917
      subSubType = exon
            location: 2628722 .... 2629792
      subSubType = exon
            location: 2629795 .... 2629917

Thanks.

**Comment by yzhernand** [comment]
Hi sufenhu9. This issue doesn't apply to this repo, so I am closing this bug. bp-utils is a set of scripts that wrap around some bioperl modules.

I suggest posting your issue on the [bioperl-live issue tracker](https://github.com/bioperl/bioperl-live/issues). Someone there might be able to help you out.
